# Generated by Django 2.0.3 on 2018-05-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcu', '0002_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.TextField(default='[]'),
        ),
    ]
