# Generated by Django 2.0.3 on 2018-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcu', '0003_profile_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isEnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instruction',
            name='isEnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='isEnable',
            field=models.BooleanField(default=True),
        ),
    ]
