# Generated by Django 2.0.3 on 2018-05-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcu', '0004_auto_20180529_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data',
        ),
    ]
