# Generated by Django 2.0.3 on 2018-05-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcu', '0006_state_isenable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='b',
        ),
        migrations.RemoveField(
            model_name='state',
            name='g',
        ),
        migrations.RemoveField(
            model_name='state',
            name='r',
        ),
    ]
