# Generated by Django 2.0.3 on 2018-06-02 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcu', '0007_auto_20180601_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='humi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='temp',
            field=models.FloatField(null=True),
        ),
    ]
