# Generated by Django 2.0.3 on 2018-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcu', '0008_auto_20180602_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='humi',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='state',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
